// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: java/guicing/proto/storage.proto

package guicing.proto;

public final class StorageProto {
  private StorageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StoreOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 next_id = 1;
    /**
     * <code>required int64 next_id = 1;</code>
     */
    boolean hasNextId();
    /**
     * <code>required int64 next_id = 1;</code>
     */
    long getNextId();

    // repeated .guicing.proto.Item item = 2;
    /**
     * <code>repeated .guicing.proto.Item item = 2;</code>
     */
    java.util.List<guicing.proto.StorageProto.Item> 
        getItemList();
    /**
     * <code>repeated .guicing.proto.Item item = 2;</code>
     */
    guicing.proto.StorageProto.Item getItem(int index);
    /**
     * <code>repeated .guicing.proto.Item item = 2;</code>
     */
    int getItemCount();
    /**
     * <code>repeated .guicing.proto.Item item = 2;</code>
     */
    java.util.List<? extends guicing.proto.StorageProto.ItemOrBuilder> 
        getItemOrBuilderList();
    /**
     * <code>repeated .guicing.proto.Item item = 2;</code>
     */
    guicing.proto.StorageProto.ItemOrBuilder getItemOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code guicing.proto.Store}
   *
   * <pre>
   * This will be used by the file store.
   * </pre>
   */
  public static final class Store extends
      com.google.protobuf.GeneratedMessage
      implements StoreOrBuilder {
    // Use Store.newBuilder() to construct.
    private Store(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Store(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Store defaultInstance;
    public static Store getDefaultInstance() {
      return defaultInstance;
    }

    public Store getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Store(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              nextId_ = input.readInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                item_ = new java.util.ArrayList<guicing.proto.StorageProto.Item>();
                mutable_bitField0_ |= 0x00000002;
              }
              item_.add(input.readMessage(guicing.proto.StorageProto.Item.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          item_ = java.util.Collections.unmodifiableList(item_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return guicing.proto.StorageProto.internal_static_guicing_proto_Store_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return guicing.proto.StorageProto.internal_static_guicing_proto_Store_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              guicing.proto.StorageProto.Store.class, guicing.proto.StorageProto.Store.Builder.class);
    }

    public static com.google.protobuf.Parser<Store> PARSER =
        new com.google.protobuf.AbstractParser<Store>() {
      public Store parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Store(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Store> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 next_id = 1;
    public static final int NEXT_ID_FIELD_NUMBER = 1;
    private long nextId_;
    /**
     * <code>required int64 next_id = 1;</code>
     */
    public boolean hasNextId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 next_id = 1;</code>
     */
    public long getNextId() {
      return nextId_;
    }

    // repeated .guicing.proto.Item item = 2;
    public static final int ITEM_FIELD_NUMBER = 2;
    private java.util.List<guicing.proto.StorageProto.Item> item_;
    /**
     * <code>repeated .guicing.proto.Item item = 2;</code>
     */
    public java.util.List<guicing.proto.StorageProto.Item> getItemList() {
      return item_;
    }
    /**
     * <code>repeated .guicing.proto.Item item = 2;</code>
     */
    public java.util.List<? extends guicing.proto.StorageProto.ItemOrBuilder> 
        getItemOrBuilderList() {
      return item_;
    }
    /**
     * <code>repeated .guicing.proto.Item item = 2;</code>
     */
    public int getItemCount() {
      return item_.size();
    }
    /**
     * <code>repeated .guicing.proto.Item item = 2;</code>
     */
    public guicing.proto.StorageProto.Item getItem(int index) {
      return item_.get(index);
    }
    /**
     * <code>repeated .guicing.proto.Item item = 2;</code>
     */
    public guicing.proto.StorageProto.ItemOrBuilder getItemOrBuilder(
        int index) {
      return item_.get(index);
    }

    private void initFields() {
      nextId_ = 0L;
      item_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasNextId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getItemCount(); i++) {
        if (!getItem(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, nextId_);
      }
      for (int i = 0; i < item_.size(); i++) {
        output.writeMessage(2, item_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, nextId_);
      }
      for (int i = 0; i < item_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, item_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static guicing.proto.StorageProto.Store parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static guicing.proto.StorageProto.Store parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static guicing.proto.StorageProto.Store parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static guicing.proto.StorageProto.Store parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static guicing.proto.StorageProto.Store parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static guicing.proto.StorageProto.Store parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static guicing.proto.StorageProto.Store parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static guicing.proto.StorageProto.Store parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static guicing.proto.StorageProto.Store parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static guicing.proto.StorageProto.Store parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(guicing.proto.StorageProto.Store prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code guicing.proto.Store}
     *
     * <pre>
     * This will be used by the file store.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements guicing.proto.StorageProto.StoreOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return guicing.proto.StorageProto.internal_static_guicing_proto_Store_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return guicing.proto.StorageProto.internal_static_guicing_proto_Store_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                guicing.proto.StorageProto.Store.class, guicing.proto.StorageProto.Store.Builder.class);
      }

      // Construct using guicing.proto.StorageProto.Store.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        nextId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (itemBuilder_ == null) {
          item_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          itemBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return guicing.proto.StorageProto.internal_static_guicing_proto_Store_descriptor;
      }

      public guicing.proto.StorageProto.Store getDefaultInstanceForType() {
        return guicing.proto.StorageProto.Store.getDefaultInstance();
      }

      public guicing.proto.StorageProto.Store build() {
        guicing.proto.StorageProto.Store result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public guicing.proto.StorageProto.Store buildPartial() {
        guicing.proto.StorageProto.Store result = new guicing.proto.StorageProto.Store(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nextId_ = nextId_;
        if (itemBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            item_ = java.util.Collections.unmodifiableList(item_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.item_ = item_;
        } else {
          result.item_ = itemBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof guicing.proto.StorageProto.Store) {
          return mergeFrom((guicing.proto.StorageProto.Store)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(guicing.proto.StorageProto.Store other) {
        if (other == guicing.proto.StorageProto.Store.getDefaultInstance()) return this;
        if (other.hasNextId()) {
          setNextId(other.getNextId());
        }
        if (itemBuilder_ == null) {
          if (!other.item_.isEmpty()) {
            if (item_.isEmpty()) {
              item_ = other.item_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureItemIsMutable();
              item_.addAll(other.item_);
            }
            onChanged();
          }
        } else {
          if (!other.item_.isEmpty()) {
            if (itemBuilder_.isEmpty()) {
              itemBuilder_.dispose();
              itemBuilder_ = null;
              item_ = other.item_;
              bitField0_ = (bitField0_ & ~0x00000002);
              itemBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemFieldBuilder() : null;
            } else {
              itemBuilder_.addAllMessages(other.item_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNextId()) {
          
          return false;
        }
        for (int i = 0; i < getItemCount(); i++) {
          if (!getItem(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        guicing.proto.StorageProto.Store parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (guicing.proto.StorageProto.Store) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 next_id = 1;
      private long nextId_ ;
      /**
       * <code>required int64 next_id = 1;</code>
       */
      public boolean hasNextId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 next_id = 1;</code>
       */
      public long getNextId() {
        return nextId_;
      }
      /**
       * <code>required int64 next_id = 1;</code>
       */
      public Builder setNextId(long value) {
        bitField0_ |= 0x00000001;
        nextId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 next_id = 1;</code>
       */
      public Builder clearNextId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nextId_ = 0L;
        onChanged();
        return this;
      }

      // repeated .guicing.proto.Item item = 2;
      private java.util.List<guicing.proto.StorageProto.Item> item_ =
        java.util.Collections.emptyList();
      private void ensureItemIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          item_ = new java.util.ArrayList<guicing.proto.StorageProto.Item>(item_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          guicing.proto.StorageProto.Item, guicing.proto.StorageProto.Item.Builder, guicing.proto.StorageProto.ItemOrBuilder> itemBuilder_;

      /**
       * <code>repeated .guicing.proto.Item item = 2;</code>
       */
      public java.util.List<guicing.proto.StorageProto.Item> getItemList() {
        if (itemBuilder_ == null) {
          return java.util.Collections.unmodifiableList(item_);
        } else {
          return itemBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .guicing.proto.Item item = 2;</code>
       */
      public int getItemCount() {
        if (itemBuilder_ == null) {
          return item_.size();
        } else {
          return itemBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .guicing.proto.Item item = 2;</code>
       */
      public guicing.proto.StorageProto.Item getItem(int index) {
        if (itemBuilder_ == null) {
          return item_.get(index);
        } else {
          return itemBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .guicing.proto.Item item = 2;</code>
       */
      public Builder setItem(
          int index, guicing.proto.StorageProto.Item value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.set(index, value);
          onChanged();
        } else {
          itemBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .guicing.proto.Item item = 2;</code>
       */
      public Builder setItem(
          int index, guicing.proto.StorageProto.Item.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .guicing.proto.Item item = 2;</code>
       */
      public Builder addItem(guicing.proto.StorageProto.Item value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.add(value);
          onChanged();
        } else {
          itemBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .guicing.proto.Item item = 2;</code>
       */
      public Builder addItem(
          int index, guicing.proto.StorageProto.Item value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.add(index, value);
          onChanged();
        } else {
          itemBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .guicing.proto.Item item = 2;</code>
       */
      public Builder addItem(
          guicing.proto.StorageProto.Item.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.add(builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .guicing.proto.Item item = 2;</code>
       */
      public Builder addItem(
          int index, guicing.proto.StorageProto.Item.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .guicing.proto.Item item = 2;</code>
       */
      public Builder addAllItem(
          java.lang.Iterable<? extends guicing.proto.StorageProto.Item> values) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          super.addAll(values, item_);
          onChanged();
        } else {
          itemBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .guicing.proto.Item item = 2;</code>
       */
      public Builder clearItem() {
        if (itemBuilder_ == null) {
          item_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          itemBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .guicing.proto.Item item = 2;</code>
       */
      public Builder removeItem(int index) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.remove(index);
          onChanged();
        } else {
          itemBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .guicing.proto.Item item = 2;</code>
       */
      public guicing.proto.StorageProto.Item.Builder getItemBuilder(
          int index) {
        return getItemFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .guicing.proto.Item item = 2;</code>
       */
      public guicing.proto.StorageProto.ItemOrBuilder getItemOrBuilder(
          int index) {
        if (itemBuilder_ == null) {
          return item_.get(index);  } else {
          return itemBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .guicing.proto.Item item = 2;</code>
       */
      public java.util.List<? extends guicing.proto.StorageProto.ItemOrBuilder> 
           getItemOrBuilderList() {
        if (itemBuilder_ != null) {
          return itemBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(item_);
        }
      }
      /**
       * <code>repeated .guicing.proto.Item item = 2;</code>
       */
      public guicing.proto.StorageProto.Item.Builder addItemBuilder() {
        return getItemFieldBuilder().addBuilder(
            guicing.proto.StorageProto.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .guicing.proto.Item item = 2;</code>
       */
      public guicing.proto.StorageProto.Item.Builder addItemBuilder(
          int index) {
        return getItemFieldBuilder().addBuilder(
            index, guicing.proto.StorageProto.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .guicing.proto.Item item = 2;</code>
       */
      public java.util.List<guicing.proto.StorageProto.Item.Builder> 
           getItemBuilderList() {
        return getItemFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          guicing.proto.StorageProto.Item, guicing.proto.StorageProto.Item.Builder, guicing.proto.StorageProto.ItemOrBuilder> 
          getItemFieldBuilder() {
        if (itemBuilder_ == null) {
          itemBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              guicing.proto.StorageProto.Item, guicing.proto.StorageProto.Item.Builder, guicing.proto.StorageProto.ItemOrBuilder>(
                  item_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          item_ = null;
        }
        return itemBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:guicing.proto.Store)
    }

    static {
      defaultInstance = new Store(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:guicing.proto.Store)
  }

  public interface ItemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 id = 1;
    /**
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     */
    long getId();

    // optional bytes serialized_item = 2;
    /**
     * <code>optional bytes serialized_item = 2;</code>
     */
    boolean hasSerializedItem();
    /**
     * <code>optional bytes serialized_item = 2;</code>
     */
    com.google.protobuf.ByteString getSerializedItem();
  }
  /**
   * Protobuf type {@code guicing.proto.Item}
   *
   * <pre>
   * This will be used by the file store and the redis store.
   * </pre>
   */
  public static final class Item extends
      com.google.protobuf.GeneratedMessage
      implements ItemOrBuilder {
    // Use Item.newBuilder() to construct.
    private Item(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Item(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Item defaultInstance;
    public static Item getDefaultInstance() {
      return defaultInstance;
    }

    public Item getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Item(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              serializedItem_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return guicing.proto.StorageProto.internal_static_guicing_proto_Item_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return guicing.proto.StorageProto.internal_static_guicing_proto_Item_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              guicing.proto.StorageProto.Item.class, guicing.proto.StorageProto.Item.Builder.class);
    }

    public static com.google.protobuf.Parser<Item> PARSER =
        new com.google.protobuf.AbstractParser<Item>() {
      public Item parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Item(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Item> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    // optional bytes serialized_item = 2;
    public static final int SERIALIZED_ITEM_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString serializedItem_;
    /**
     * <code>optional bytes serialized_item = 2;</code>
     */
    public boolean hasSerializedItem() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes serialized_item = 2;</code>
     */
    public com.google.protobuf.ByteString getSerializedItem() {
      return serializedItem_;
    }

    private void initFields() {
      id_ = 0L;
      serializedItem_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, serializedItem_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, serializedItem_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static guicing.proto.StorageProto.Item parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static guicing.proto.StorageProto.Item parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static guicing.proto.StorageProto.Item parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static guicing.proto.StorageProto.Item parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static guicing.proto.StorageProto.Item parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static guicing.proto.StorageProto.Item parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static guicing.proto.StorageProto.Item parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static guicing.proto.StorageProto.Item parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static guicing.proto.StorageProto.Item parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static guicing.proto.StorageProto.Item parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(guicing.proto.StorageProto.Item prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code guicing.proto.Item}
     *
     * <pre>
     * This will be used by the file store and the redis store.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements guicing.proto.StorageProto.ItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return guicing.proto.StorageProto.internal_static_guicing_proto_Item_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return guicing.proto.StorageProto.internal_static_guicing_proto_Item_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                guicing.proto.StorageProto.Item.class, guicing.proto.StorageProto.Item.Builder.class);
      }

      // Construct using guicing.proto.StorageProto.Item.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        serializedItem_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return guicing.proto.StorageProto.internal_static_guicing_proto_Item_descriptor;
      }

      public guicing.proto.StorageProto.Item getDefaultInstanceForType() {
        return guicing.proto.StorageProto.Item.getDefaultInstance();
      }

      public guicing.proto.StorageProto.Item build() {
        guicing.proto.StorageProto.Item result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public guicing.proto.StorageProto.Item buildPartial() {
        guicing.proto.StorageProto.Item result = new guicing.proto.StorageProto.Item(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.serializedItem_ = serializedItem_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof guicing.proto.StorageProto.Item) {
          return mergeFrom((guicing.proto.StorageProto.Item)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(guicing.proto.StorageProto.Item other) {
        if (other == guicing.proto.StorageProto.Item.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasSerializedItem()) {
          setSerializedItem(other.getSerializedItem());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        guicing.proto.StorageProto.Item parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (guicing.proto.StorageProto.Item) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 id = 1;
      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // optional bytes serialized_item = 2;
      private com.google.protobuf.ByteString serializedItem_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes serialized_item = 2;</code>
       */
      public boolean hasSerializedItem() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes serialized_item = 2;</code>
       */
      public com.google.protobuf.ByteString getSerializedItem() {
        return serializedItem_;
      }
      /**
       * <code>optional bytes serialized_item = 2;</code>
       */
      public Builder setSerializedItem(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        serializedItem_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes serialized_item = 2;</code>
       */
      public Builder clearSerializedItem() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serializedItem_ = getDefaultInstance().getSerializedItem();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:guicing.proto.Item)
    }

    static {
      defaultInstance = new Item(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:guicing.proto.Item)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_guicing_proto_Store_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_guicing_proto_Store_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_guicing_proto_Item_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_guicing_proto_Item_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n java/guicing/proto/storage.proto\022\rguic" +
      "ing.proto\";\n\005Store\022\017\n\007next_id\030\001 \002(\003\022!\n\004i" +
      "tem\030\002 \003(\0132\023.guicing.proto.Item\"+\n\004Item\022\n" +
      "\n\002id\030\001 \002(\003\022\027\n\017serialized_item\030\002 \001(\014B\035\n\rg" +
      "uicing.protoB\014StorageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_guicing_proto_Store_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_guicing_proto_Store_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_guicing_proto_Store_descriptor,
              new java.lang.String[] { "NextId", "Item", });
          internal_static_guicing_proto_Item_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_guicing_proto_Item_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_guicing_proto_Item_descriptor,
              new java.lang.String[] { "Id", "SerializedItem", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
